// <auto-generated />
namespace SantImerio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class eventi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(eventi));
        
        string IMigrationMetadata.Id
        {
            get { return "201609121308001_eventi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
